### ISSUE TITLE
JavaScript assignment [partially] live

### ISSUE THREAD

**Issue by sudowork** [Duke-PL-Course/JavaScript#2]
@Duke-PL-Course 
We have written up the first 4 problems of the [JavaScript assignment](https://github.com/Duke-PL-Course/JavaScript/blob/master/2013-02-03-assignment.md). Please take a look at it prior to class so you have a chance to ask questions. We realize that the last homework assignment may have been rather challenging, so we tried to lighten the load on this one. We also want you to have the opportunity to ask questions as soon as possible, so we are releasing this as we create it.

A lot of the questions have a focus on some functions that are essential to functional programming (map, filter, reduce). We want to prepare you for some of the more functional languages we will deal with, so writing your own version of these three functions will hopefully aid your understanding. The other ones deal with testing your basic JavaScript syntax, as well as understanding prototype-based inheritance (to be released). Finally, the bonus question will involve implementing the `waterfall` control structure as seen in [**async.js**](https://github.com/caolan/async). `waterfall` is similar to the `series` function; however, it allows you to pass additional parameters to each successive callback.

Good luck and see you in class Tuesday!

**Comment by sudowork** [comment]
As a side note, we will be covering Prolog this upcoming Tuesday, but we will also allow some time at the beginning of class to review JavaScript or Ruby.

**Comment by peggyl** [comment]
What's the deadline for the JavaScript assignment?

**Comment by sudowork** [comment]
@peggy-li , @Duke-PL-Course 
Wednesday, February 13, 2013 at 23:59:59 EST.

**Comment by peggyl** [comment]
Was this really due yesterday?! I remember hearing it would be Friday or Sunday. (Not to mention, Q5 isn't even up yet.)

**Comment by sudowork** [comment]
@peggy-li whoops. Meant to say a week from yesterday. Lesson learned, don't answer questions while sleep deprived.

**Comment by yangsu** [comment]
@Duke-PL-Course 
The assignment is complete. We have decided to remove the 5th problem. Here's our post about the assignment, including notes about the bonus problem and instructions for updating your forked repos if you've forked before today.
